# Generated by Django 2.2.3 on 2019-08-15 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '产品信息', 'verbose_name_plural': '产品信息'},
        ),
    ]
